<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'key'          => 'essentials',
                'name'         => 'Author Essentials',
                'price'        => 997,
                'description'  => 'KDP-ready publishing essentials for your first release.',
                'badge'        => 'ESSENTIALS',
                'button_text'  => 'Start with Essentials',
                'features'     => [
                    'Proofread + edit',
                    'Full-wrap cover design',
                    'Print + eBook formatting',
                    'KDP setup & upload',
                    'A+ Content basics',
                ],
                'is_featured' => false,
                'is_active'   => true,
                'sort_order'  => 1,
            ],
            [
                'key'          => 'bestseller',
                'name'         => 'Bestseller Bundle',
                'price'        => 2997,
                'description'  => 'Sales-ready publishing plus launch momentum.',
                'badge'        => 'PROFESSIONAL',
                'button_text'  => 'Choose the Bundle',
                'features'     => [
                    'Everything in Essentials',
                    'Developmental editing support',
                    'KDP + IngramSpark',
                    '90-day Amazon Ads campaign',
                    'Launch strategy & assets',
                    'Project-managed delivery',
                ],
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 2,
            ],
            [
                'key'          => 'empire',
                'name'         => 'Empire Builder',
                'price'        => 4997,
                'description'  => 'Author-brand expansion across formats and campaigns.',
                'badge'        => 'PREMIUM',
                'button_text'  => 'Build the Empire',
                'features'     => [
                    'Everything in Bestseller Bundle',
                    'Audiobook production',
                    'Author website',
                    'PR & podcast outreach',
                    'Ongoing ads management',
                ],
                'is_featured' => false,
                'is_active'   => true,
                'sort_order'  => 3,
            ],
            [
                'key'          => 'ghost-starter',
                'name'         => 'Starter Manuscript',
                'price'        => 1497,
                'description'  => 'Professional book ghostwriting up to 20,000 words.',
                'badge'        => 'GHOSTWRITING',
                'button_text'  => 'Choose Starter Manuscript',
                'features'     => [
                    'Up to 20,000 words',
                    '4 weeks planned turnaround',
                    'Project brief and agreed outline',
                    'Scheduled author feedback checkpoints',
                    'Clean manuscript handover',
                ],
                'is_featured' => false,
                'is_active'   => true,
                'sort_order'  => 4,
            ],
            [
                'key'          => 'ghost-full',
                'name'         => 'Full Novel',
                'price'        => 2997,
                'description'  => 'Professional book ghostwriting up to 45,000 words.',
                'badge'        => 'GHOSTWRITING',
                'button_text'  => 'Choose Full Novel',
                'features'     => [
                    'Up to 45,000 words',
                    '9 weeks planned turnaround',
                    'Project brief and agreed outline',
                    'Scheduled author feedback checkpoints',
                    'Clean manuscript handover',
                ],
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 5,
            ],
            [
                'key'          => 'ghost-epic',
                'name'         => 'Epic Creation',
                'price'        => 4997,
                'description'  => 'Professional book ghostwriting up to 80,000 words.',
                'badge'        => 'GHOSTWRITING',
                'button_text'  => 'Choose Epic Creation',
                'features'     => [
                    'Up to 80,000 words',
                    '13 weeks planned turnaround',
                    'Project brief and agreed outline',
                    'Scheduled author feedback checkpoints',
                    'Clean manuscript handover',
                ],
                'is_featured' => false,
                'is_active'   => true,
                'sort_order'  => 6,
            ],
            [
                'key'          => 'editing-fresh',
                'name'         => 'Fresh Eyes (Proofread)',
                'price'        => 150,
                'description'  => 'Professional proofread for near-final manuscripts up to 30,000 words.',
                'badge'        => 'EDITING',
                'button_text'  => 'Get Started',
                'features'     => [
                    'Line edit',
                    'Proofreading',
                    'Plagiarism check',
                    'Editing summary report',
                    '1 revision round',
                    '7 days delivery',
                ],
                'is_featured' => false,
                'is_active'   => true,
                'sort_order'  => 7,
            ],
            [
                'key'          => 'editing-deep',
                'name'         => 'Deep Clean (Proofread + Edit)',
                'price'        => 300,
                'description'  => 'Deep copy editing for manuscripts up to 50,000 words.',
                'badge'        => 'EDITING',
                'button_text'  => 'Get Started',
                'features'     => [
                    'Everything in Fresh Eyes',
                    'Deep copy editing',
                    'Style and flow improvements',
                    'Consistency checks',
                    '2 revision rounds',
                    '10 days delivery',
                ],
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 8,
            ],
            [
                'key'          => 'editing-makeover',
                'name'         => 'Full Makeover (Copy Edit)',
                'price'        => 500,
                'description'  => 'Full copy edit for manuscripts up to 80,000 words.',
                'badge'        => 'EDITING',
                'button_text'  => 'Get Started',
                'features'     => [
                    'Everything in Deep Clean',
                    'Full copy edit',
                    'Structural suggestions',
                    'Voice and tone refinement',
                    '2 revision rounds',
                    '2 weeks delivery',
                ],
                'is_featured' => false,
                'is_active'   => true,
                'sort_order'  => 9,
            ],
            [
                'key'          => 'ghost-format-clean',
                'name'         => 'Clean & Simple',
                'price'        => 147,
                'description'  => 'Clean layout styling for short fiction, novellas and simple text-only books up to 25k words, 3 revisions.',
                'badge'        => 'FORMATTING',
                'button_text'  => 'Order Now',
                'features'     => [
                    'Up to 25k words',
                    '3 revisions',
                    'Print PDF + EPUB delivery',
                ],
                'is_featured' => false,
                'is_active'   => true,
                'sort_order'  => 10,
            ],
            [
                'key'          => 'ghost-format-enhanced',
                'name'         => 'Enhanced Layout',
                'price'        => 227,
                'description'  => 'Chapter styling, enhanced TOC and scene breaks for full-length novels up to 50k words, 3 revisions.',
                'badge'        => 'FORMATTING',
                'button_text'  => 'Order Now',
                'features'     => [
                    'Up to 50k words',
                    '3 revisions',
                    'Chapter styling',
                    'Print PDF + EPUB delivery',
                ],
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 11,
            ],
            [
                'key'          => 'ghost-format-complex',
                'name'         => 'Complex Design',
                'price'        => 377,
                'description'  => 'Sidebars, tables and custom chapter templates for nonfiction, workbooks and design-rich formats up to 60k words, 3 revisions.',
                'badge'        => 'FORMATTING',
                'button_text'  => 'Order Now',
                'features'     => [
                    'Up to 60k words',
                    '3 revisions',
                    'Custom chapter templates',
                    'Print PDF + EPUB delivery',
                ],
                'is_featured' => false,
                'is_active'   => true,
                'sort_order'  => 12,
            ],
            [
                'key'          => 'kids-format-pro',
                'name'         => 'Illustrated Pro',
                'price'        => 249,
                'description'  => 'Professional children\'s book formatting for illustrated picture books.',
                'badge'        => 'CHILDREN\'S FORMATTING',
                'button_text'  => 'Order Now',
                'features'     => [
                    'Up to 32 pages',
                    'Standard trim size (8.5 x 8.5)',
                    'Illustration-ready layout',
                    'Print PDF + EPUB delivery',
                    '3 revision rounds',
                ],
                'is_featured' => false,
                'is_active'   => true,
                'sort_order'  => 13,
            ],
        ];

        DB::table('plans')->truncate();

        foreach ($plans as $plan) {
            Plan::create($plan);
        }
    }
}
