<?php

namespace Database\Seeders;

use App\Models\PortfolioItem;
use Illuminate\Database\Seeder;

class PortfolioItemSeeder extends Seeder
{
    public function run(): void
    {
        PortfolioItem::truncate();

        $items = [
            // ── Book Cover Design (vertical) ──
            [
                'title'                 => 'Whispers in the Dark',
                'author'                => 'Elena Matthews',
                'category'              => 'romance',
                'portfolio_category_id' => 1,
                'type_label'            => 'Cover · Romance',
                'is_featured'           => true,
                'is_active'             => true,
                'sort_order'            => 1,
            ],
            [
                'title'                 => 'The Last Horizon',
                'author'                => 'James Calloway',
                'category'              => 'fantasy',
                'portfolio_category_id' => 1,
                'type_label'            => 'Cover · Fantasy',
                'is_featured'           => true,
                'is_active'             => true,
                'sort_order'            => 2,
            ],
            [
                'title'                 => 'Silent Witness',
                'author'                => 'Sarah Brooks',
                'category'              => 'thriller',
                'portfolio_category_id' => 1,
                'type_label'            => 'Cover · Thriller',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 3,
            ],
            [
                'title'                 => 'Midnight Shadows',
                'author'                => 'David Chen',
                'category'              => 'mystery',
                'portfolio_category_id' => 1,
                'type_label'            => 'Cover · Mystery',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 4,
            ],
            [
                'title'                 => 'Heartstrings',
                'author'                => 'Amara Williams',
                'category'              => 'romance',
                'portfolio_category_id' => 1,
                'type_label'            => 'Cover · Romance',
                'is_featured'           => true,
                'is_active'             => true,
                'sort_order'            => 5,
            ],
            [
                'title'                 => 'Kingdom of Ashes',
                'author'                => 'R.K. Thornton',
                'category'              => 'fantasy',
                'portfolio_category_id' => 1,
                'type_label'            => 'Cover · Fantasy',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 6,
            ],
            [
                'title'                 => 'Beyond the Shadows',
                'author'                => 'Laura Bennett',
                'category'              => 'non-fiction',
                'portfolio_category_id' => 1,
                'type_label'            => 'Cover · Non-Fiction',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 7,
            ],

            // ── Interior Formatting (horizontal) ──
            [
                'title'                 => 'The Art of Mindful Living',
                'author'                => 'Dr. Sarah Mitchell',
                'category'              => 'self-help',
                'portfolio_category_id' => 2,
                'type_label'            => 'Interior · Self-Help',
                'is_featured'           => true,
                'is_active'             => true,
                'sort_order'            => 8,
            ],
            [
                'title'                 => 'Digital Marketing Mastery',
                'author'                => 'Michael Torres',
                'category'              => 'business',
                'portfolio_category_id' => 2,
                'type_label'            => 'Interior · Business',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 9,
            ],
            [
                'title'                 => 'Journey to Inner Peace',
                'author'                => 'Priya Sharma',
                'category'              => 'self-help',
                'portfolio_category_id' => 2,
                'type_label'            => 'Interior · Self-Help',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 10,
            ],
            [
                'title'                 => 'The Entrepreneur Handbook',
                'author'                => 'Robert Hayes',
                'category'              => 'business',
                'portfolio_category_id' => 2,
                'type_label'            => 'Interior · Business',
                'is_featured'           => true,
                'is_active'             => true,
                'sort_order'            => 11,
            ],
            [
                'title'                 => 'Healing Through Nutrition',
                'author'                => 'Dr. Amy Foster',
                'category'              => 'health',
                'portfolio_category_id' => 2,
                'type_label'            => 'Interior · Health',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 12,
            ],
            [
                'title'                 => 'Modern Leadership Principles',
                'author'                => 'James Walker',
                'category'              => 'business',
                'portfolio_category_id' => 2,
                'type_label'            => 'Interior · Business',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 13,
            ],

            // ── Children's Illustrations (horizontal) ──
            [
                'title'                 => 'The Curious Little Fox',
                'author'                => 'Emma Clarke',
                'category'              => 'children',
                'portfolio_category_id' => 3,
                'type_label'            => 'Illustration · Children',
                'is_featured'           => true,
                'is_active'             => true,
                'sort_order'            => 14,
            ],
            [
                'title'                 => 'Benny the Brave Bear',
                'author'                => 'Sophie Anderson',
                'category'              => 'children',
                'portfolio_category_id' => 3,
                'type_label'            => 'Illustration · Children',
                'is_featured'           => true,
                'is_active'             => true,
                'sort_order'            => 15,
            ],
            [
                'title'                 => 'Starlight Adventures',
                'author'                => 'Lucas Martin',
                'category'              => 'children',
                'portfolio_category_id' => 3,
                'type_label'            => 'Illustration · Children',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 16,
            ],
            [
                'title'                 => 'The Magic Garden',
                'author'                => 'Olivia Brown',
                'category'              => 'children',
                'portfolio_category_id' => 3,
                'type_label'            => 'Illustration · Children',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 17,
            ],
            [
                'title'                 => 'Captain Whiskers',
                'author'                => 'Noah Davis',
                'category'              => 'children',
                'portfolio_category_id' => 3,
                'type_label'            => 'Illustration · Children',
                'is_featured'           => true,
                'is_active'             => true,
                'sort_order'            => 18,
            ],
            [
                'title'                 => 'Dreamland Tales',
                'author'                => 'Mia Johnson',
                'category'              => 'children',
                'portfolio_category_id' => 3,
                'type_label'            => 'Illustration · Children',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 19,
            ],

            // ── Published Books (vertical) ──
            [
                'title'                 => 'Echoes of Yesterday',
                'author'                => 'Daniel Hughes',
                'category'              => 'fiction',
                'portfolio_category_id' => 4,
                'type_label'            => 'Published · Fiction',
                'is_featured'           => true,
                'is_active'             => true,
                'sort_order'            => 20,
            ],
            [
                'title'                 => 'The Silent Path',
                'author'                => 'Grace Mitchell',
                'category'              => 'memoir',
                'portfolio_category_id' => 4,
                'type_label'            => 'Published · Memoir',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 21,
            ],
            [
                'title'                 => 'Strength in Faith',
                'author'                => 'Pastor John Reed',
                'category'              => 'religious',
                'portfolio_category_id' => 4,
                'type_label'            => 'Published · Religious',
                'is_featured'           => true,
                'is_active'             => true,
                'sort_order'            => 22,
            ],
            [
                'title'                 => 'The Hidden Kingdom',
                'author'                => 'Alex Morgan',
                'category'              => 'fantasy',
                'portfolio_category_id' => 4,
                'type_label'            => 'Published · Fantasy',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 23,
            ],
            [
                'title'                 => 'Cooking with Love',
                'author'                => 'Maria Garcia',
                'category'              => 'cookbook',
                'portfolio_category_id' => 4,
                'type_label'            => 'Published · Cookbook',
                'is_featured'           => true,
                'is_active'             => true,
                'sort_order'            => 24,
            ],
            [
                'title'                 => 'Uncharted Waters',
                'author'                => 'Thomas Wright',
                'category'              => 'fiction',
                'portfolio_category_id' => 4,
                'type_label'            => 'Published · Fiction',
                'is_featured'           => false,
                'is_active'             => true,
                'sort_order'            => 25,
            ],
        ];

        foreach ($items as $item) {
            PortfolioItem::create($item);
        }
    }
}
